[build]
  functions = "netlify/functions"
  publish = "."

  [build.environment]
    NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
     "pg",
    "@veramo/credential-ld",
    "@transmute/jsonld",
    "jsonld",
    "@digitalbazaar/http-client"
  ]

[[redirects]]
  from = "/credential-offer"
  to = "/.netlify/functions/credential-offer"
  status = 200

[[redirects]]
  from = "/.well-known/openid-credential-issuer"
  to = "/.netlify/functions/openid-credential-issuer"
  status = 200




