[build]
  functions = "netlify/functions"
  publish = "."

  # Set the Node version used for build & functions runtime
  [build.environment]
    NODE_VERSION = "18"

[functions]
  # Use esbuild for bundling
  node_bundler = "esbuild"

  # Externalize fragile ESM deps so esbuild does not mangle them
  external_node_modules = [
    "@transmute/jsonld",
    "jsonld",
    "@digitalbazaar/http-client",
    "@digitalbazaar/credentials-context"
  ]

[[redirects]]
  from = "/credential-offer"
  to = "/.netlify/functions/credential-offer"
  status = 200

[[redirects]]
  from = "/.well-known/openid-credential-issuer"
  to = "/.netlify/functions/openid-credential-issuer"
  status = 200




